app = "tx-notes"
primary_region = "waw"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1

[env]
CORS_ORIGIN = "https://tx-notes.fly.dev"
