name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies (client)
        run: |
          cd client
          yarn install --frozen-lockfile
      - name: Install dependencies (server)
        run: |
          cd server
          yarn install --frozen-lockfile
      - name: Build client
        run: |
          cd client
          yarn build
      - name: Build server
        run: |
          cd server
          yarn build
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
